### PR TITLE
2861741 Workflow to run e2e tests

### PR DESCRIPTION
**Pull request by tejaswip-msft**
# What
Workflow to run E2E tests 
Whenever a PR with UI changes is raised, this workflow will fail at the first attempt and a comment on the PR is added advising the owner to add a "ui change" label to the PR to trigger the update snapshots workflow as shown below
CommentOnPR

Once the label is added, the update snapshots workflow is triggered, which will push the updated screenshots as a commit to the PR. This commit will trigger the E2E workflow again, this time the e2e tests are tested against the updated screenshots. 
AddingLabel

# Why

# How Tested
Tested with a forked repository
https://github.com/tejaswip-msft/Sample/actions/runs/2518368847

# Process & policy checklist

- [X] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Comment by ralphgabrinao** [comment]
Failed to pass the UI Test. If this PR is for UI change and the error is snapshot mismatch, please add "ui change" label to the PR for updating the snapshot.

**Comment by hansung-msft** [comment]
Will this PR include the screenshot (snapshot) that created from the action?

**Comment by tejaswip-msft** [comment]
> Will this PR include the screenshot (snapshot) that created from the action?

yes Han thats correct

**Review by ralphgabrinao — APPROVED** [review]

**Comment by hansung-msft** [comment]
Just tested to see if the workflow gets trigger when I remove the `ui change' tag and re-add.

**Review by hansung-msft — APPROVED** [review]

**Pull request merged**
