### PR TITLE
Add duration to Room

### PR DESCRIPTION
**Pull request by ralphgabrinao**
# What

Room is valid for 1 hour. If attempting to join a Room that has not yet started or is expired, the CallComposite will render the "You have left the call" screen as if the user left the call.

# Why

Currently the room is not set a duration. The room should be valid for 1 hour after its creation

# How Tested

Locally and deployed to Azure in a region with a different timezone. Confirmed that the Rooms API uses UTC

Also manually tested E2E, starting a call from Home and confirming that I can join the Room as the presenter and attendee.

2022-12-12 13_52_03-Postman

# Process & policy checklist

- [x] I have updated the project documentation to reflect my changes if necessary.
- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) documentation.

**Does this PR contain ARM Template changes?**

- [ ] I have verified deploying using the ARM Template
- [ ] I have tested the deployed app end to end

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Review by tejaswip-msft — COMMENTED** [review]
Please add in the description about what the behaviour is if room is expired

**Comment by ralphgabrinao** [comment]
@tejaswip-msft Will do. I will wait a few more minutes and let the Room expire and I will give it a try

**Review by tejaswip-msft — APPROVED** [review]
LGTM

**Comment by dailam-msft** [comment]
> @tejaswip-msft Will do. I will wait a few more minutes and let the Room expire and I will give it a try

Helo, were we able to check what the behaviour is when the room expires and we try to join with same link? Can you update whatever behaviour saw here in the description or comments

**Comment by ralphgabrinao** [comment]
@dailam-msft Yup it is in the description -- If attempting to join a Room that has not yet started or is expired, the CallComposite will render the "You have left the call" screen as if the user left the call.

**Comment by tejaswip-msft** [comment]
> Room is valid for 1 hour. If attempting to join a Room that has not yet started or is expired, the CallComposite will render the "You have left the call" screen as if the user left the call.

Its mentioned in the description: 
Room is valid for 1 hour. If attempting to join a Room that has not yet started or is expired, the CallComposite will render the "You have left the call" screen as if the user left the call.

**Comment by dailam-msft** [comment]
> @dailam-msft Yup it is in the description -- If attempting to join a Room that has not yet started or is expired, the CallComposite will render the "You have left the call" screen as if the user left the call.

Ahh.. ok.. Well, not really a fan of "you have left the call" when actually its expired - but I guess it's pretty minor. Thanks for clarifying!

**Review by dailam-msft — APPROVED** [review]

**Comment by ralphgabrinao** [comment]
@dailam-msft Ya me too. It is default behavior of the CallComposite. We were planning of implementing custom screens for the "Appointment has not started" and "Appointment has ended" scenarios, but we are holding off on that work.

**Pull request merged**
