### PR TITLE
Add README for Rooms

### PR DESCRIPTION
**Pull request by ralphgabrinao**
# What
README that explains the use of Rooms within the Sample. 

# Why
This README will be linked from the Sample Builder.

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) documentation.

**Does this PR contain ARM Template changes?**

- [ ] I have verified deploying using the ARM Template
- [ ] I have tested the deployed app end to end

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

### CODE REVIEW

**Review by tejaswip-msft — APPROVED** [review]

**Review by dailam-msft — COMMENTED** [review]
The rooms copy invite link SS should be changed for consistency as this is not how the option currently shows up on the CallComposite

**Comment by ralphgabrinao** [comment]
@dailam-msft Can you please clarify what you mean? I took the screenshot yesterday with the latest changes in main.

**Comment by dailam-msft** [comment]
> @dailam-msft Can you please clarify what you mean? I took the screenshot yesterday with the latest changes in main.

Deploying on local (main branch) did not pop-out a side panel - which was the reason for my comment. 
image

**Comment by ralphgabrinao** [comment]
@dailam-msft I just deployed a fresh app from GH to Azure and I see the side panel. Perhaps you have a different version of UI lib locally?

**Review by hansung-msft — APPROVED** [review]

**Pull request merged**
